import os
import uuid
import sqlite3
import json
from flask import Flask, request, jsonify
from groq import Groq
from dotenv import load_dotenv
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from scoring import calculate_stylometrics, calculate_weighted_veto_score, calculate_burstiness
from multimodal_scoring import calculate_template_conformity, calculate_descriptive_verbosity

load_dotenv()

app = Flask(__name__)

# Rate Limiting setup (10 per minute for submissions)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["200 per day"],
    storage_uri="memory://",
)
DB_PATH = 'provenance_guard.db'

# Initialize Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def get_llm_score(text):
    """
    Calls Groq to assess the likelihood of the text being AI-generated.
    Returns a score between 0.0 (Human) and 1.0 (AI).
    """
    prompt = f"""
    Analyze the following text and determine if it was written by a human or generated by an AI.
    Provide a score between 0.0 and 1.0, where 0.0 is definitely human and 1.0 is definitely AI.
    Return ONLY a JSON object with the keys "score" and "reasoning".

    Text:
    {text[:2000]}  # Truncate to save tokens
    """

    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are an expert AI content detector. Respond only in JSON."},
                {"role": "user", "content": prompt},
            ],
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"}
        )
        result = json.loads(chat_completion.choices[0].message.content)
        return float(result.get("score", 0.5))
    except Exception as e:
        print(f"Error calling Groq: {e}")
        return 0.5 # Default to uncertain on error

def get_transparency_label(confidence, is_verified=False):
    """
    Returns the transparency label based on the confidence score.
    Prefixes with 'Verified Provenance: ' if creator is verified.
    """
    if confidence <= 0.3:
        label = "Human-Authored: This content displays the stylistic variability characteristic of human writing."
    elif confidence >= 0.71:
        label = "AI-Generated: This content matches patterns consistently associated with large language model output."
    else:
        label = "Attribution Neutral: Our analysis found mixed signals regarding the origin of this content."

    if is_verified:
        return f"Verified Provenance: {label}"
    return label

@app.route('/submit', methods=['POST'])
@limiter.limit("10 per minute")
def submit():
    data = request.get_json()
    if not data or 'text' not in data or 'creator_id' not in data:
        return jsonify({"error": "Missing text or creator_id"}), 400

    text = data['text']
    creator_id = data['creator_id']
    content_type = data.get('content_type', 'text')
    content_id = str(uuid.uuid4())

    # Check Verification Status
    conn = get_db_connection()
    verified_status = conn.execute('SELECT status FROM verified_creators WHERE creator_id = ?', (creator_id,)).fetchone()
    is_verified = (verified_status['status'] == 'active') if verified_status else False

    multimodal_scores = None
    stylo_human_score = 0.5
    burst_score = 0.5
    template_score = None
    verbosity_score = None

    # Signal Pipeline
    llm_ai_score = get_llm_score(text)

    if content_type == 'image_description':
        template_score = calculate_template_conformity(text)
        verbosity_score = calculate_descriptive_verbosity(text)
        multimodal_scores = {
            'template_score': template_score,
            'verbosity_score': verbosity_score
        }
    else:
        stylo_human_score = calculate_stylometrics(text)
        burst_score = calculate_burstiness(text)

    # Weighted-Veto Scoring Engine
    confidence = calculate_weighted_veto_score(
        llm_ai_score,
        stylo_human_score,
        burst_score,
        content_type=content_type,
        multimodal_scores=multimodal_scores
    )

    attribution = "likely_ai" if confidence >= 0.71 else ("likely_human" if confidence <= 0.3 else "uncertain")
    label = get_transparency_label(confidence, is_verified)

    # Audit Logging
    conn.execute('''
        INSERT INTO audit_log (
            content_id, creator_id, text, content_type, attribution, confidence,
            llm_score, stylo_score, template_score, verbosity_score, is_verified
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        content_id, creator_id, text, content_type, attribution, confidence,
        llm_ai_score, stylo_human_score if content_type == 'text' else None,
        template_score, verbosity_score, 1 if is_verified else 0
    ))
    conn.commit()
    conn.close()

    response = {
        "content_id": content_id,
        "content_type": content_type,
        "attribution": attribution,
        "confidence": round(confidence, 2),
        "llm_score": round(llm_ai_score, 2),
        "label": label,
        "provenance_certificate": is_verified
    }

    if content_type == 'image_description':
        response["template_score"] = round(template_score, 2)
        response["verbosity_score"] = round(verbosity_score, 2)
    else:
        response["stylo_score"] = round(stylo_human_score, 2)

    return jsonify(response)

@app.route('/verify', methods=['POST'])
def verify():
    """
    Verification endpoint for creators.
    Requires a secret token mimic.
    """
    data = request.get_json()
    if not data or 'creator_id' not in data or 'token' not in data:
        return jsonify({"error": "Missing creator_id or token"}), 400

    # Secret token check (similar to X-Admin-Key)
    if data['token'] != 'super-secret-verification-token':
        return jsonify({"error": "Invalid verification token"}), 401

    creator_id = data['creator_id']

    conn = get_db_connection()
    conn.execute('''
        INSERT INTO verified_creators (creator_id, status)
        VALUES (?, 'active')
        ON CONFLICT(creator_id) DO UPDATE SET status = 'active'
    ''', (creator_id,))
    conn.commit()
    conn.close()

    return jsonify({
        "status": "verified",
        "creator_id": creator_id,
        "message": "Creator successfully verified for Provenance Certificate."
    })

@app.route('/appeal', methods=['POST'])
def appeal():
    data = request.get_json()
    if not data or 'content_id' not in data or 'creator_reasoning' not in data:
        return jsonify({"error": "Missing content_id or creator_reasoning"}), 400

    content_id = data['content_id']
    reasoning = data['creator_reasoning']
    new_label = "Humanity Verification in Progress (Under Review): A creator has contested the automated label."

    conn = get_db_connection()
    # Check if entry exists
    entry = conn.execute('SELECT * FROM audit_log WHERE content_id = ?', (content_id,)).fetchone()
    if not entry:
        conn.close()
        return jsonify({"error": "Content ID not found"}), 404

    # Update Status and reasoning
    conn.execute('''
        UPDATE audit_log
        SET status = 'under_review', appeal_reasoning = ?
        WHERE content_id = ?
    ''', (reasoning, content_id))
    conn.commit()
    conn.close()

    return jsonify({
        "status": "under_review",
        "content_id": content_id,
        "label": new_label
    })

@app.route('/dashboard', methods=['GET'])
def get_dashboard():
    # Simulated admin check
    admin_key = request.headers.get('X-Admin-Key')
    if admin_key != 'super-secret-admin-key':
        return jsonify({"error": "Unauthorized"}), 401

    conn = get_db_connection()
    stats = conn.execute('''
        SELECT
            COUNT(*) as total,
            SUM(CASE WHEN attribution = 'likely_ai' THEN 1 ELSE 0 END) as ai_count,
            SUM(CASE WHEN attribution = 'likely_human' THEN 1 ELSE 0 END) as human_count,
            SUM(CASE WHEN attribution = 'uncertain' THEN 1 ELSE 0 END) as uncertain_count,
            SUM(CASE WHEN status = 'under_review' THEN 1 ELSE 0 END) as appeal_count,
            SUM(CASE WHEN is_verified = 1 THEN 1 ELSE 0 END) as verified_count,
            AVG(confidence) as average_confidence
        FROM audit_log
    ''').fetchone()
    conn.close()

    data = dict(stats)
    total = data['total'] or 0
    ai_count = data['ai_count'] or 0
    human_count = data['human_count'] or 0
    appeal_count = data['appeal_count'] or 0

    # Calculated Analytics (Deep Module behavior)
    data['appeal_rate'] = round(appeal_count / total, 4) if total > 0 else 0
    data['ai_to_human_ratio'] = round(ai_count / human_count, 2) if human_count > 0 else (ai_count if ai_count > 0 else 0)
    data['average_confidence'] = round(data['average_confidence'] or 0, 2)

    return jsonify(data)

@app.route('/log', methods=['GET'])
def get_log():
    # Simulated admin check
    admin_key = request.headers.get('X-Admin-Key')
    if admin_key != 'super-secret-admin-key':
        return jsonify({"error": "Unauthorized"}), 401

    conn = get_db_connection()
    logs = conn.execute('SELECT * FROM audit_log ORDER BY timestamp DESC').fetchall()
    conn.close()

    return jsonify([dict(log) for log in logs])

if __name__ == '__main__':
    app.run(port=5000, debug=True)
